package com.olidev.synapse_mobile.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF00CCCC)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF5FF3F3)
val onPrimaryContainerLight = Color(0xFF002828)

val secondaryLight = Color(0xFF0055FF)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD9E2FF)
val onSecondaryContainerLight = Color(0xFF001945)
val tertiaryLight = Color(0xFFFFBA00)
val onTertiaryLight = Color(0xFF261900)
val tertiaryContainerLight = Color(0xFFFFDF8A)
val onTertiaryContainerLight = Color(0xFF332400)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF4FBFA)
val onBackgroundLight = Color(0xFF161D1D)
val surfaceLight = Color(0xFFF4FBFA)
val onSurfaceLight = Color(0xFF161D1D)
val surfaceVariantLight = Color(0xFFDAE5E4)
val onSurfaceVariantLight = Color(0xFF3F4948)
val outlineLight = Color(0xFF6F7979)
val outlineVariantLight = Color(0xFFBEC9C8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3231)
val inverseOnSurfaceLight = Color(0xFFECF2F1)
val inversePrimaryLight = Color(0xFF80D5D4)
val surfaceDimLight = Color(0xFFD5DBDA)
val surfaceBrightLight = Color(0xFFF4FBFA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F4)
val surfaceContainerLight = Color(0xFFE9EFEE)
val surfaceContainerHighLight = Color(0xFFE3E9E9)
val surfaceContainerHighestLight = Color(0xFFDDE4E3)

val quaternaryLight = Color(0xFF6750A4)
val onQuaternaryLight = Color(0xFFFFFFFF)
val quaternaryContainerLight = Color(0xFFEADDFF)

val quinaryLight = Color(0xFF2EB800)
val onQuinaryLight = Color(0xFFFFFFFF)
val quinaryContainerLight = Color(0xFFB6F29F)

val senaryLight = Color(0xFFBC004B)
val onSenaryLight = Color(0xFFFFFFFF)
val senaryContainerLight = Color(0xFFFFD9DE)

val primaryDark = Color(0xFF00CCCC)
val onPrimaryDark = Color(0xFF003737)
val primaryContainerDark = Color(0xFF005C5C)
val onPrimaryContainerDark = Color(0xFF6FF6F6)
val secondaryDark = Color(0xFFB0C6FF)
val onSecondaryDark = Color(0xFF002D71)
val secondaryContainerDark = Color(0xFF00419E)
val onSecondaryContainerDark = Color(0xFFD9E2FF)
val tertiaryDark = Color(0xFFFFBA00)
val onTertiaryDark = Color(0xFF412D00)
val tertiaryContainerDark = Color(0xFF704F00)
val onTertiaryContainerDark = Color(0xFFFFE09E)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF091010)
val onBackgroundDark = Color(0xFFDDE4E3)
val surfaceDark = Color(0xFF091010)
val onSurfaceDark = Color(0xFFDDE4E3)
val surfaceVariantDark = Color(0xFF3F4948)
val onSurfaceVariantDark = Color(0xFFBEC9C8)
val outlineDark = Color(0xFF889392)
val outlineVariantDark = Color(0xFF3F4948)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDDE4E3)
val inverseOnSurfaceDark = Color(0xFF2B3231)
val inversePrimaryDark = Color(0xFF006A6A)
val surfaceDimDark = Color(0xFF0E1514)
val surfaceBrightDark = Color(0xFF343A3A)
val surfaceContainerLowestDark = Color(0xFF050A0A)
val surfaceContainerLowDark = Color(0xFF101717)
val surfaceContainerDark = Color(0xFF161D1D)
val surfaceContainerHighDark = Color(0xFF202828)
val surfaceContainerHighestDark = Color(0xFF2A3232)


val quaternaryDark = Color(0xFFBF7BFF)
val onQuaternaryDark = Color(0xFF4B0082)
val quaternaryContainerDark = Color(0xFF5D00B0)
val onQuaternaryContainerDark = Color(0xFFEADDFF)

val quinaryDark = Color(0xFF99D681)
val onQuinaryDark = Color(0xFF043900)
val quinaryContainerDark = Color(0xFF065300)

val senaryDark = Color(0xFFFFB2BE)
val onSenaryDark = Color(0xFF660025)
val senaryContainerDark = Color(0xFF900037)